# Generated by Django 4.2.2 on 2023-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="task1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="task",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
